### ISSUE TITLE
CVE on golang.org/x/net/http2 v0.20.0

### ISSUE THREAD

**Issue by navas-op** [operator-framework/ansible-operator-plugins#64]
Security vulnerabilities on golang.org/x/net/ v0.20.0
Which have been fixed on fixed in 0.23.0.

https://github.com/operator-framework/ansible-operator-plugins/blob/main/go.mod#L89

Can this package be upgraded?

**Comment by chiragkyal** [comment]
Hey @navas-op, I checked that the [master](https://github.com/operator-framework/ansible-operator-plugins/blob/42b5d80c75f1ddda8f2dbe1629b9454d366a8d6a/go.mod#L88) is now using `golang.org/x/net v0.24.0` . Are we good to close this ?

**Comment by acornett21** [comment]
- Relates: #67
